### ISSUE TITLE
The partition of the UIEB dataset

### ISSUE THREAD

**Issue by xjq-flare** [zhoujingchun03/HCLR-Net#1]
Thanks for your nice work. Could you please provide the accurate partition of the UIEB dataset used in the paper?

**Comment by Hikari0608** [comment]
It's great to hear your compliments!  @xjq-flare 🤩

The following are the divisions of the UIEB dataset:

Train(800) and Val(90)
https://huggingface.co/datasets/Hikari0608/UIEB

Test(60) 
https://huggingface.co/datasets/Hikari0608/Eval

You can use the python package `datasets` to convert downloaded files to RAW images and then train them using our code, please refer to: 🤗https://huggingface.co/docs/datasets/image_load 

Please quote our paper if it helps you, thanks!
